-- Documents the five pg_cron jobs driving the app's nightly/scheduled work.
-- Applied directly via mcp__Supabase__execute_sql / cron.alter_job (not
-- through this file) since they invoke Edge Functions by URL rather than
-- touching schema; this file exists so anyone rebuilding from scratch has
-- the exact commands, including the timeout fix below.
--
-- IMPORTANT: net.http_post defaults to a 5-second timeout_milliseconds. The
-- Edge Functions these jobs call (dailyPriceUpdate especially — fetches an
-- external Google Sheet, then loops through every profile's funds) routinely
-- take longer than 5s, so the default caused pg_net to give up waiting and
-- log a timeout — sporadically leaving the night's price/balance update
-- incomplete or unrecorded even though the function kept running server-side.
-- All three jobs must pass a generous timeout_milliseconds (60000) to avoid
-- this. Do not omit it when recreating or editing these jobs.
--
-- TIMING (daily-price-update): this job ran once, at 01:00 UTC = 9:00pm ET,
-- and the live price sheet refreshes around 8:50pm (its own "Last Updated"
-- column showed 8:49:21 PM). Ten minutes of margin against a CDN-cached
-- endpoint is no margin at all, so the job read the PREVIOUS market day's
-- prices every night and the whole account sat a full market day behind
-- tsp.gov.
--
-- MEASURED: the sheet's "Last Updated" stamp has read 8:49:21 PM and 8:49:22 PM
-- on separate days — a fixed daily refresh — and the evidence says that stamp
-- is CENTRAL, not Eastern. On 8/22 the 01:00 UTC run read the previous day's
-- prices; 01:00 UTC is 8:49pm-plus-11-minutes only if the stamp is Eastern, so
-- it can't be. Under Central it lands at 01:49 UTC, 11 minutes AFTER that run —
-- which matches what the job actually saw. Confirmed from the other side on
-- 8/26: the 02:00 UTC run (11 minutes past 01:49) succeeded first try.
--
-- So the earliest the data can exist is ~8:50pm Central. A run at 8:00pm
-- Central is 49 minutes too early and can only ever skip.
--
-- It now runs as a LADDER of attempts rather than one shot:
--   01:00 UTC  8:00pm CT  — the requested time; skips until the sheet moves earlier
--   01:55 UTC  8:55pm CT  — primary; ~6 min after the sheet publishes
--   02:00, 02:40, 03:00, 03:40 UTC — catch-ups through 10:40pm CT
-- (pg_cron schedules in UTC, so these all shift an hour in Central terms
-- across DST; the ladder is wide enough to absorb that.)
--
-- Running the same day repeatedly is safe by design, which is what makes the
-- ladder work at all:
--   - dailyPriceUpdate refuses to record prices whose sheet date isn't the day
--     being recorded, so an attempt that fires before the sheet refreshes skips
--     instead of banking stale prices;
--   - each fund is re-valued from its unit count, so repricing is idempotent;
--   - contributions are applied only when no daily_balances row exists yet for
--     the day, so they can't be double-counted by a later rung.
--
-- Do not add a rung at 04:00 UTC or later. dailyPriceUpdate derives the market
-- day it is recording from the ET clock at run time, so it must still be the
-- previous ET calendar day when the job fires. 03:40 UTC is 11:40pm ET under
-- EDT — the last usable slot. 04:00 UTC is midnight EDT, which would stamp the
-- prices with the wrong date.

-- select cron.schedule(
--   'daily-price-update', '0,55 1 * * *', $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/dailyPriceUpdate',
--     headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer <anon-key>','apikey','<anon-key>'),
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );

-- Final rung, for a night the sheet publishes late. Safe to run after a
-- successful pass, for the reasons listed under TIMING above.
-- select cron.schedule(
--   'daily-price-update-retry', '0,40 2,3 * * *', $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/dailyPriceUpdate',
--     headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer <anon-key>','apikey','<anon-key>'),
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );

-- mfwPriceUpdate runs twice — once early (6am ET) and again at the
-- originally-programmed time (8am ET) — since mutual fund NAVs can settle at
-- different points overnight; running it twice catches a price that wasn't
-- posted yet at the first check.
-- select cron.schedule(
--   'mfw-price-update-early', '0 10 * * *', $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/mfwPriceUpdate',
--     headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer <anon-key>','apikey','<anon-key>'),
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );

-- select cron.schedule(
--   'mfw-price-update', '0 12 * * *', $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/mfwPriceUpdate',
--     headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer <anon-key>','apikey','<anon-key>'),
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );

-- select cron.schedule(
--   'nightly-email-job', '*/15 * * * *', $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/nightlyEmailJob',
--     headers := jsonb_build_object('Content-Type','application/json','Authorization','Bearer <anon-key>','apikey','<anon-key>'),
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );
